package main

import (
	"context"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/restic/restic/internal/data"
	"github.com/restic/restic/internal/errors"
	"github.com/restic/restic/internal/global"
	"github.com/restic/restic/internal/rechunker"
	"github.com/restic/restic/internal/restic"
	"github.com/restic/restic/internal/ui"
)

type CopyPlanOptions struct {
	data.SnapshotFilter
}

func newRechunkPlanCommand(globalOptions *global.Options) *cobra.Command {
	var opts CopyPlanOptions
	cmd := &cobra.Command{
		Use:   "rechunk-copy-plan [flags] [snapshotID [snapshotID]] ...",
		Short: "generate lists for rechunk-copy",
		Long: `
generate lists for rechunk-copy. File list is generated by sorting by descending number
of contributing blobs. Once the blobs are all loaded and cached, it will be checked if
other files can be rechunked / stored in target repoitory.

If no snapshot list is given, the whole repository is analysed.

EXIT STATUS
===========

Exit status is 0 if the command was successful.
Exit status is 1 if there was any error.
Exit status is 10 if the repository does not exist.
Exit status is 11 if the repository is already locked.
Exit status is 12 if the password is incorrect.
`,
		DisableAutoGenTag: true,
		GroupID:           cmdGroupDefault,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCopyPlan(cmd.Context(), opts, *globalOptions, args, globalOptions.Term)
		},
	}
	opts.AddFlags(cmd.Flags())

	return cmd
}

func (opts *CopyPlanOptions) AddFlags(f *pflag.FlagSet) {
	initMultiSnapshotFilter(f, &opts.SnapshotFilter, true)
}

func runCopyPlan(ctx context.Context, opts CopyPlanOptions, gopts global.Options, args []string, term ui.Terminal) error {
	printer := ui.NewProgressPrinter(false, gopts.Verbosity, term)

	// open repository, no lock
	ctx, repo, unlock, err := openWithReadLock(ctx, gopts, true, printer)
	if err != nil {
		return err
	}
	defer unlock()

	// load all snapshot files
	snapshotLister, err := restic.MemorizeList(ctx, repo, restic.SnapshotFile)
	if err != nil {
		return err
	}

	// index needs to be loaded
	if err = repo.LoadIndex(ctx, printer); err != nil {
		return err
	}

	selectedSnaps := make([]*data.Snapshot, 0, 100)
	for sn := range FindFilteredSnapshots(ctx, snapshotLister, repo, &opts.SnapshotFilter, args, printer) {
		selectedSnaps = append(selectedSnaps, sn)
	}
	if len(selectedSnaps) == 0 {
		return errors.Fatal("snapshotfilter active but no snapshot selected")
	}

	// create a new 'CpInfo' instance
	cpInfo := rechunker.NewCPInfo(selectedSnaps, printer)

	// build plan
	filePrimary, fileSecondary, packList, err := cpInfo.CreateCopyPlan(ctx, repo)
	if err != nil {
		return err
	}

	// finale: report summaries
	lenInfo := cpInfo.GetLengths()

	blobSize := uint64(0)
	for blob := range cpInfo.BlobToFileID {
		blobSize += uint64(cpInfo.IndexInfo[blob].Length)
	}
	printer.S("%7d selected snapshots", lenInfo.LengthSelectedSnapshots)
	printer.S("%7d unique files in selected snapshots", len(filePrimary)+len(fileSecondary))
	printer.S("%7d primary file downloads to start", len(filePrimary))
	printer.S("%7d secondary files to process", len(fileSecondary))
	printer.S("%7d data packfiles to load", len(packList))
	printer.S("%7d used blobs with size %11s", lenInfo.LengthUsedBlobs, ui.FormatBytes(blobSize))
	printer.S("%7d index entries", lenInfo.LengthIndexInfo)

	return nil
}
