package main

import (
  // system
  "context"
  "encoding/binary"
  "encoding/hex"
  "errors"
  "fmt"
  "io"
  "os"
  "os/exec"
  "path/filepath"
  "regexp"
  "sort"
  "strconv"
  "strings"
  "time"
  "crypto/sha256"

  //argparse
  "github.com/spf13/cobra"

  // restic library
  "github.com/wplapper/restic/library/repository/pack"
  "github.com/wplapper/restic/library/repository"
  "github.com/wplapper/restic/library/restic"

  // sets
  "github.com/deckarep/golang-set/v2"
)

type CreateDB struct {
  Debug  string
  Sha256 bool
  Timing bool
  All    bool
}

type SHA256 [32]byte

const (
  DBG_SNAPSHOT = 0x001
  DBG_PACKFILE = 0x002
  DBG_INDEX    = 0x004
  DBG_NAMES    = 0x008
  DBG_METADATA = 0x010
  DBG_CONTENTS = 0x020
  DBG_CONFIG   = 0x040
  DBG_SHA256   = 0x080
  DBG_CRETABLE = 0x100
  DBG_CREINDEX = 0x200
)

var createDBOptions CreateDB

var cmdCreateDB = &cobra.Command{
  Use:   "wpl-create-db [flags]",
  Short: "create sql statements for a SQLite database to be generated",
  Long: `create sql statements for a SQLite database to be generated.
Use the format of the sqlite3 .dump format for outputting the data straight
into sqlite:
/usr/bin/sqlite3 [database-name] < [input stream generated by this command].
os/exec.Command("/usr/bin/sqlite3", database-name) is used,
wehereby STDIN is connected to a pipe (exec.StdinPipe()).

EXIT STATUS
===========

Exit status is 0 if the command was successful, and non-zero if there was any error.
`,
  DisableAutoGenTag: false,
  RunE: func(cmd *cobra.Command, args []string) error {
    return runCreateDB(cmd.Context(), globalOptions)
  },
}

func init() {
  cmdRoot.AddCommand(cmdCreateDB)
  f := cmdCreateDB.Flags()
  f.StringVarP(&createDBOptions.Debug, "debug", "D", "0", "debug options")
  f.BoolVarP(&createDBOptions.Sha256, "sha256", "S", false, "do not create sha256 contents")
  f.BoolVarP(&createDBOptions.Timing, "timing", "T", false, "create timings")
  f.BoolVarP(&createDBOptions.All, "all", "A", false, "do all repositories")
}

type Driver struct {
  stdin       io.WriteCloser
  Debug       int
  RecordCount *int
}

func runCreateDB(ctx context.Context, gopts GlobalOptions) error {
  if createDBOptions.All {
    for _, repoName := range WplRepositoryList {
      Printf("repo %s\n", repoName)
      if repoName[0:6] == "/media" {
        // execute usr/bin/ncat -z new-PC 22 -w 1s
        pingCmd := exec.Command("/usr/bin/ncat", "-z", "new-PC", "22", "-w", "1s")
        err := pingCmd.Run()
        if err != nil {
          Printf("Could not ping host new-PC on port 22\n")
          continue
        }
      }

      gopts.Repo = repoName
      res := runOneDatabase(ctx, gopts)
      if res != nil {
        continue
      }
    }
    return nil
  } else {
    return runOneDatabase(ctx, gopts)
  }
  return nil
}

func runOneDatabase(ctx context.Context, gopts GlobalOptions) error {

  var (
    repositoryData   RepositoryData
    dataBaseFilename string
    err              error
    startTime        time.Time
    recordCount      int
  )

  // startup
  startTime = time.Now()
  gOptions = gopts
  init_repositoryData(&repositoryData)
  recordCount = 0

  // convert Debug string to int
  debug_options_str := createDBOptions.Debug
  debug_options_int := 0
  re := regexp.MustCompile("^[a-fA-F0-9]+$")
  if re.FindString(debug_options_str) != "" {
    temp, _ := strconv.ParseInt(debug_options_str, 16, 64)
    debug_options_int = int(temp)
  }

  // step 1: open repository
  repo, err := OpenRepository(ctx, gopts)
  if err != nil {
    return err
  }
  Verboseff("Repository is %s\n", globalOptions.Repo)
  Verboseff("%-48s %7.1f seconds\n", "repository open",
    time.Since(startTime).Seconds())

  dataBaseFilename = selectDatabaseName(gopts)
  Verboseff("database is %s\n", dataBaseFilename)

  // check if file /home/wplapper/restic/all_index_repo.bin exists
  // if so, then create repositoryData.BlobToIndex[blob.ID] and
  // repositoryData.IndexToBlob first!
  err = processAllIndexRepoFile(&repositoryData)
  if err != nil {
    return err
  }

  // step 2: gather the base information
  err = gather_base_data_repo(repo, gopts, ctx, &repositoryData,
    createDBOptions.Timing)
  if err != nil {
    return err
  }
  Verboseff("%-48s %7.1f seconds\n", "gather base data",
    time.Since(startTime).Seconds())

  good, err := checkDatabaseDates(dataBaseFilename, repo, &repositoryData)
  if good {
    Printf("database is up-to-date\n")
    return nil
  }

  //Printf("db is '%s'\n", dataBaseFilename)
  _, err = os.Create(dataBaseFilename)
  if err != nil {
    Printf("Cant Create database - reason '%v'\n", err)
    return err
  }

  t1 := time.Now()
  sqlCmd := exec.Command("/usr/bin/sqlite3", dataBaseFilename)
  stdin, err := sqlCmd.StdinPipe()
  if err != nil {
    Printf("Can't Create Pipe to STDIN - reason '%v'\n", err)
    return err
  }

  go func() {
    defer stdin.Close()
    driver := &Driver{stdin: stdin, Debug: debug_options_int, RecordCount: &recordCount}
    // generate the input stream for the SQLite database
    GatherDatabaseData(ctx, repo, driver, &repositoryData, startTime)
  }()

  // wait for sqlite3 execution to finish
  out, err := sqlCmd.CombinedOutput()
  if err != nil {
    Printf("CombinedOutput failed - reason '%v'\n", err)
    Printf("%s\n", out)
    return err
  }
  if len(out) > 0 {
    Printf("%s\n", out)
  }

  Verboseff("%8d records for SQLite3 stream\n", recordCount)
  Verboseff("%-48s %7.1f seconds\n", "*** sqlite3 process ***",
    time.Since(t1).Seconds())
  return nil
}

func GatherDatabaseData(ctx context.Context, repo *repository.Repository,
  driver *Driver, repositoryData *RepositoryData, startTime time.Time) (err error) {
  /*
   * sequence of events is as follows:
   * the in-core file will be generated in the steps
   * 00-startup
   * 01-create_tables
   * 02-snapshots
   * 03-packfiles
   * 04-index_repo
   * 05-names
   * metaBlobSorter
   * 09-createSha56
   * 06-meta_data_storage (needs all the above dependencies)
   * 06-meta_data_storage (needs all the above dependencies)
   * 07-contents
   * 08-config (single row table)
   * 12-create_index
   * 13-finale
   *
   * The following tables can easily be created by running a few SQL statements:
   * children
   * snap_blobs
   * dir_names, for use in creating fullname
   */
  var sha256Content map[CmpIndex]int

  step_00_startup(driver)
  step_01_createTables(driver)
  step_02_snapshots(driver, repositoryData, startTime)              // 02-snapshots
  step_03_04_ix_files(driver, repositoryData, ctx, repo, startTime) // 03-packfiles, 04-index_repo
  namesMap := step_05_names(driver, repositoryData, startTime)
  metaBlobs := MetaBlobSorter(repositoryData)

  if createDBOptions.Sha256 {
    sha256Content = map[CmpIndex]int{}
  } else {
    sha256Content = step_09_createSha56(driver, repositoryData)
  }

  step_06_meta_data_storage(ctx, repo, driver, repositoryData, namesMap,
    metaBlobs, sha256Content, startTime)
  step_07_contents(driver, repositoryData, metaBlobs, startTime)
  step_08_repo_config(driver, repositoryData, repo, !createDBOptions.Sha256)
  step_12_createIndex(driver)

  step_13_finale(driver)
  Verboseff("%-48s %7.1f seconds\n", "end create stream",
    time.Since(startTime).Seconds())
  return nil
}

// start the export file
func step_00_startup(tx *Driver) {
  io.WriteString(tx.stdin, "PRAGMA foreign_keys=OFF;\n")
  io.WriteString(tx.stdin, "BEGIN EXCLUSIVE TRANSACTION;\n")
  *(tx.RecordCount) += 2
}

// and CREATE TABLEs
func step_01_createTables(tx *Driver) {
  for _, sql := range CreateTablesSlice {
    io.WriteString(tx.stdin, sql+";\n")
    if (tx.Debug & DBG_CRETABLE) == DBG_CRETABLE {
      Printf("%s;\n", sql)
    }
    *(tx.RecordCount) += 1
  }
}

// gather data about snapshots
func step_02_snapshots(tx *Driver, repositoryData *RepositoryData,
  startTime time.Time) (snapMap map[restic.ID]int) {

  /*
    type SnapshotRow struct {
      Id        int
      Snap_id   []byte
      Snap_short string (8 bytes long)
      Snap_time string
      Snap_host string
      Snap_fsys string
      Snap_root []byte
    }
  */
  high_id := 1
  snapMap = map[restic.ID]int{}
  // repositoryData.Snaps is already sorted
  for _, sn := range repositoryData.Snaps {
    ID := sn.ID
    snap_id_as_string := hex.EncodeToString(ID[:])
    line := fmt.Sprintf(
      "INSERT INTO snapshots VALUES(%d,X'%s','%s','%s','%s','%s',X'%s');\n",
      high_id,
      snap_id_as_string,
      snap_id_as_string[:8],
      sn.Time.Format(time.DateTime),
      sn.Hostname, sn.Paths[0],
      hex.EncodeToString(sn.Tree[:]))
    io.WriteString(tx.stdin, line)
    if (tx.Debug & DBG_SNAPSHOT) == DBG_SNAPSHOT {
      Printf("%s", line)
    }
    *(tx.RecordCount) += 1
    snapMap[ID] = high_id
    high_id++
  }
  Verboseff("%-35s %7d rows %7.1f seconds\n", "INSERT INTO snapshots",
    high_id-1, time.Since(startTime).Seconds())
  return snapMap
}

type PackfileRecordRow struct {
  Type string
}

// gather information about packfiles and the index structure
func step_03_04_ix_files(tx *Driver, repositoryData *RepositoryData,
  ctx context.Context, repo *repository.Repository, start time.Time) {

  // extract packfiles with their sizes from the Master Index
  // 'repo_packs' is map[restic.ID]int64
  repo_packs, err := pack.Size(ctx, repo, false)
  if err != nil {
    Printf("error in pack.Size - error is %v", err)
    return
  }

  // local containers
  packMap := map[restic.ID]PackfileRecordRow{}
  packSet := mapset.NewThreadUnsafeSet[int]()
  packToBlobSet := map[IntID]mapset.Set[IntID]{}
  for _, ih := range repositoryData.IndexHandle {
    if packSet.Add(int(ih.pack_index)) {
      pack_ID := repositoryData.IndexToBlob[ih.pack_index]
      row := PackfileRecordRow{ih.Type.String()}
      packMap[pack_ID] = row
    }
    if _, ok := packToBlobSet[ih.pack_index]; !ok {
      packToBlobSet[ih.pack_index] = mapset.NewThreadUnsafeSet[IntID]()
    }
    packToBlobSet[ih.pack_index].Add(ih.blob_index)
  }

  // convert to Slice and sort
  packSlice := packSet.ToSlice()
  sort.Ints(packSlice)
  /*CREATE TABLE packfiles (
      id INTEGER PRIMARY KEY,             -- the primary key
      packfile_id BLOB NOT NULL,          -- the packfile ID, UNIQUE INDEX, [32]byte
      blob_count INTEGER NOT NULL,        -- number of blobs in packfile
      type TEXT NOT NULL,                 -- type of packfile data/tree
      packfile_size INT
  )*/

  count := 0
  for _, pack_index := range packSlice {
    pack_ID := repositoryData.IndexToBlob[IntID(pack_index)]
    //line := fmt.Sprintf("INSERT INTO packfiles(id,packfile_id,blob_count,type,packfile_size) VALUES(%d,X'%s',%d,'%s',%d);\n",
    line := fmt.Sprintf("INSERT INTO packfiles VALUES(%d,X'%s',%d,'%s',%d);\n",
      pack_index,
      hex.EncodeToString(pack_ID[:]),
      packToBlobSet[IntID(pack_index)].Cardinality(),
      packMap[pack_ID].Type,
      int(repo_packs[pack_ID]),
    )
    io.WriteString(tx.stdin, line)
    if (tx.Debug & DBG_PACKFILE) == DBG_PACKFILE {
      Printf("%s", line)
    }
    *(tx.RecordCount) += 1
    count++
  }
  Verboseff("%-35s %7d rows %7.1f seconds\n", "INSERT INTO packfiles",
    count, time.Since(start).Seconds())

  /*type IndexRepoRecordRow struct {
    Id                 IntID
    Blob               []byte // == UNIQUE
    Type               string
    Length             int
    UncompressedLength int
    Pack__id           int // back pointer to packfiles
  }*/

  // collect all blob indices - tree and data
  blobSet := mapset.NewThreadUnsafeSet[int]()
  for _, ih := range repositoryData.IndexHandle {
    blobSet.Add(int(ih.blob_index))
  }

  // convert to Slice and sort
  blobSlice := blobSet.ToSlice()
  sort.Ints(blobSlice)
  count = 0
  for _, blob_index := range blobSlice {
    blob_ID := repositoryData.IndexToBlob[IntID(blob_index)]
    ih := repositoryData.IndexHandle[blob_ID]

    line := fmt.Sprintf("INSERT INTO index_repo VALUES(%d,X'%s','%s',%d,%d,%d);\n",
      blob_index,
      hex.EncodeToString(blob_ID[:]),
      ih.Type.String(),
      ih.size,
      ih.UncompressedLength,
      ih.pack_index)
    io.WriteString(tx.stdin, line)
    if (tx.Debug & DBG_INDEX) == DBG_INDEX {
      Printf("%s", line)
    }
    *(tx.RecordCount) += 1
    count++
  }

  Verboseff("%-35s %7d rows %7.1f seconds\n", "INSERT INTO index_repo",
    count, time.Since(start).Seconds())
}

// collect all names from repository
func step_05_names(tx *Driver, repositoryData *RepositoryData,
  start time.Time) (namesMap map[string]int) {

  // gather names
  namesSet := mapset.NewThreadUnsafeSet[string]()
  for _, fileList := range repositoryData.DirectoryMap {
    for _, node := range fileList {
      namesSet.Add(node.name)
    }
  }

  // convert Set to Slice for sorting
  namesSlice := namesSet.ToSlice()
  sort.Strings(namesSlice)

  high_id := 1
  namesMap = map[string]int{}
  for _, name := range namesSlice {
    var nameDB string
    nameDB = name
    if strings.Index(nameDB, "'") >= 0 {
      nameDB = strings.ReplaceAll(nameDB, "'", "''")
    }
    line := fmt.Sprintf("INSERT INTO names VALUES(%d,'%s');\n", high_id, nameDB)
    io.WriteString(tx.stdin, line)
    if (tx.Debug & DBG_NAMES) == DBG_NAMES {
      Printf("%s", line)
    }
    *(tx.RecordCount) += 1
    namesMap[name] = high_id
    high_id++
  }

  Verboseff("%-35s %7d rows %7.1f seconds\n", "INSERT INTO names",
    high_id-1, time.Since(start).Seconds())
  return namesMap
}

// create a Slice of sorted metaBlobs - tree index records
func MetaBlobSorter(repositoryData *RepositoryData) (metaBlobs []IntID) {
  metaBlobsSet := mapset.NewThreadUnsafeSet[IntID]()
  for _, ih := range repositoryData.IndexHandle {
    if ih.Type == restic.TreeBlob {
      metaBlobsSet.Add(ih.blob_index)
    }
  }
  metaBlobs = metaBlobsSet.ToSlice()
  sort.Slice(metaBlobs, func(i, j int) bool {
    return metaBlobs[i] < metaBlobs[j]
  })
  return metaBlobs
}

func step_06_meta_data_storage(ctx context.Context, repo *repository.Repository,
  tx *Driver, repositoryData *RepositoryData, namesMap map[string]int,
  metaBlobs []IntID, sha256StoreIndex map[CmpIndex]int, start time.Time) (err error) {

  /*
    type MetaDataStorageRow struct {
      Id       IntID // ptr to 'index_repo' TABLE
      Position int   // offset in nodes list
      Name__id int   // ptr to 'names' TABLE
      // copied from original Node:
      Type        string
      Mode        os.FileMode
      Mtime       string
      Inode       uint64
      DeviceID    uint64
      Size        uint64
      Links       uint64
      Subtree__id IntID
      LinkTarget  string
    }
  */
  high_id := 1
  for _, meta_blob := range metaBlobs {
    for position, node := range repositoryData.DirectoryMap[meta_blob] {
      var size, links, subtree__id, linkTarget, sha256 string

      // NULL column processing
      sha256 = "NULL"
      cmp_ix := CmpIndex{meta_blob, position}
      if len(sha256StoreIndex) > 0 && node.Type == "file" && node.size > 0 {
        index, ok := sha256StoreIndex[cmp_ix]
        if ok {
          sha256 = fmt.Sprintf("%d", index)
        } else {
          Printf("index entry for sha256 %+v not found!\n", cmp_ix)
        }
      }
      if node.size == 0 {
        size = "NULL"
      } else {
        size = fmt.Sprintf("%d", node.size)
      }
      if node.Links == 0 {
        links = "NULL"
      } else {
        links = fmt.Sprintf("%d", node.Links)
      }
      if node.Type == "dir" {
        subtree__id = fmt.Sprintf("%d", node.subtree_ID)
      } else {
        subtree__id = "NULL"
      }
      if node.LinkTarget == "" {
        linkTarget = "NULL"
      } else {
        linkTarget = node.LinkTarget
        if strings.Index(linkTarget, "'") >= 0 {
          linkTarget = strings.ReplaceAll(linkTarget, "'", "''")
        }
        linkTarget = fmt.Sprintf("'%s'", linkTarget)
      }
      // end NULL processing

      line := fmt.Sprintf(
        //                                   1  2  3  4   5   6   7   8  9 10 11 12 13 14
        "INSERT INTO meta_data_store VALUES(%d,%d,%d,%d,'%s',%d,'%s',%d,%d,%s,%s,%s,%s,%s);\n",
        high_id,                            //  1
        meta_blob,                          //  2
        position,                           //  3
        namesMap[node.name],                //  4
        node.Type,                          //  5
        node.Mode,                          //  6
        node.mtime.Format(time.DateTime),   //  7
        node.inode,                         //  8
        node.DeviceID,                      //  9
        // possible NULL values
        sha256,                             // 10
        size,                               // 11
        links,                              // 12
        subtree__id,                        // 13
        linkTarget)                         // 14
      io.WriteString(tx.stdin, line)
      if (tx.Debug & DBG_METADATA) == DBG_METADATA {
        Printf("%s", line)
      }
      *(tx.RecordCount) += 1
      high_id++
    }
  }

  Verboseff("%-35s %7d rows %7.1f seconds\n", "INSERT INTO meta_data_store",
    high_id-1, time.Since(start).Seconds())
  return nil
}

// collect contents from repository
func step_07_contents(tx *Driver, repositoryData *RepositoryData,
  metaBlobs []IntID, start time.Time) {

  /*type ContentsRecordRow struct {
    Blob__id IntID // map back to index_repo.id (owning directory / meta_blob)
    Position int   // with triple (Id_blob, Position, Offset) == UNIQUE
    Offset   int
    Data__id IntID // map back to index_repo.id (data)
  }*/

  high_id := 1
  for _, meta_blob := range metaBlobs {
    for position, node := range repositoryData.DirectoryMap[meta_blob] {
      for offset, cont_value := range node.content {
        line := fmt.Sprintf("INSERT INTO contents VALUES(%d,%d,%d,%d,%d);\n",
          high_id,
          meta_blob,
          position,
          offset,
          cont_value)
        io.WriteString(tx.stdin, line)
        if (tx.Debug & DBG_CONTENTS) == DBG_CONTENTS {
          Printf("%s", line)
        }
        *(tx.RecordCount) += 1
        high_id++
      }
    }
  }
  Verboseff("%-35s %7d rows %7.1f seconds\n", "INSERT INTO contents",
    high_id-1, time.Since(start).Seconds())
}

/*CREATE TABLE config (
     id INTEGER PRIMARY KEY,            -- the primary key = 1
     repo_id TEXT NOT NULL,             -- repository ID
     chunker_polynomial TEXT,           -- chunker polynomial for encoding
     repo_path TEXT,                    -- fullpath to repo
     sha256_context TEXT,               -- enable / disable sha256_content
     empty_node_id INTEGER,             -- points to index_repo(EMPTY_NODE_ID)
     last_snap_time TEXT,               -- youngest snap
     last_index_time TEXT,              -- youngest index change
     last_meta_cache TEXT               -- most recent cache meta data timestamp
)*/
// config TABLE, one row
func step_08_repo_config(tx *Driver, repositoryData *RepositoryData,
  repo *repository.Repository, sha256 bool) {
  config := repo.Config()
  chunker_polynomial := fmt.Sprintf("%v", config.ChunkerPolynomial) // 0x...
  // globalOptions.Repo
  var (
    sha56Create   string
    empty_node_id IntID
    ok            bool
  )

  if sha256 {
    sha56Create = "true"
  } else {
    sha56Create = "false"
  }

  if empty_node_id, ok = repositoryData.BlobToIndex[EMPTY_NODE_ID]; !ok {
    empty_node_id = IntID(0)
  }

  changeTimes, err := findLatestChanges(repo, repositoryData)
  if err != nil {
    return
  }

  line := fmt.Sprintf("INSERT INTO config VALUES(%d,'%s','%s','%s','%s',%d,'%s','%s');\n",
    1,
    config.ID,
    chunker_polynomial[2:],
    globalOptions.Repo,
    sha56Create,
    empty_node_id,
    changeTimes.youngSnapTime.Format(time.DateTime),
    changeTimes.youngIndexRecord.Format(time.DateTime))
  io.WriteString(tx.stdin, line)
  if (tx.Debug & DBG_CONFIG) == DBG_CONFIG {
    Printf("%s", line)
  }
  *(tx.RecordCount) += 1
}

type CmpIndex struct {
  blob_index IntID
  position   int
}

// Sha56 table for distinct contents entries
func step_09_createSha56(tx *Driver, repositoryData *RepositoryData) (sha256StoreIndex map[CmpIndex]int) {

  // is return value!
  sha256StoreIndex = map[CmpIndex]int{}
  // set up local conatiners
  sha256MapIndex := map[restic.ID]int{}
  sha256MapLength := map[restic.ID]int{}
  sliceSha256 := [][32]byte{}

  //loop start: convert all content IntIDs into one sha256 ID
  var (
    index, saved_position int
    ok                    bool
  )

  // we could make for files with single data_blob : sha256Content =
  // sha256 of data_blob
  index = 1
  var sha256Content restic.ID

  for blob_index, fileSlice := range repositoryData.DirectoryMap {
    for posi, meta := range fileSlice {
      if meta.Type == "file" && meta.size > 0 {
        if len(meta.content) == 1 {
          sha256Content = repositoryData.IndexToBlob[meta.content[0]]
        } else {
          sha256Content = ConvertContent(meta.content)
        }
        if saved_position, ok = sha256MapIndex[sha256Content]; !ok {
          sha256MapIndex[sha256Content] = index
          sha256MapLength[sha256Content] = len(meta.content)
          saved_position = index
          index++
          sliceSha256 = append(sliceSha256, sha256Content)
        }
        sha256StoreIndex[CmpIndex{blob_index, posi}] = saved_position
      }
    }
  }

  // write out
  for _, value := range sliceSha256 {
    line := fmt.Sprintf("INSERT INTO sha256_content VALUES(%d,X'%s',%d);\n",
      sha256MapIndex[value],
      hex.EncodeToString(value[:]),
      sha256MapLength[value])
    io.WriteString(tx.stdin, line)
    if (tx.Debug & DBG_SHA256) == DBG_SHA256 {
      Printf("%s", line)
    }
    *(tx.RecordCount) += 1
  }
  Verboseff("%-35s %7d rows\n", "INSERT INTO sha256_content", index)
  return sha256StoreIndex
}

// create all INDEX structures after all data have been inserted
func step_12_createIndex(tx *Driver) {
  for _, sql := range CreateIndexSlice {
    io.WriteString(tx.stdin, sql+";\n")
    if (tx.Debug & DBG_CREINDEX) == DBG_CREINDEX {
      Printf("%s;\n", sql)
    }
    *(tx.RecordCount) += 1
  }
}

// database export final steps
func step_13_finale(tx *Driver) {
  io.WriteString(tx.stdin, "COMMIT;\n")
  // CREATE left out secondary TABLE entries
  io.WriteString(tx.stdin, ".read /home/wplapper/restic/db/sql/create_missing_tables.sql\n")
  *(tx.RecordCount) += 1
}

// table definitions
var CreateTablesSlice = []string{
  `CREATE TABLE snapshots (
    id INTEGER PRIMARY KEY,             -- ID of snapshots row
    snap_id    BLOB NOT NULL,           -- snap ID, UNIQUE INDEX
    snap_short TEXT NOT NULL,           -- snap ID, first 8 character as string
    snap_time  TEXT NOT NULL,           -- time of snap, truncated to seconds
    snap_host  TEXT NOT NULL,           -- host which is to be backep up
    snap_fsys  TEXT NOT NULL,           -- filesystem to be backup up
    snap_root  BLOB NOT NULL            -- the root of the snap
    --CONSTRAINT ux_snapshots_id          UNIQUE(snap_id),
    --CONSTRAINT ux_snapshots_short       UNIQUE(snap_short)
)`,

  `CREATE TABLE packfiles (
    id INTEGER PRIMARY KEY,             -- the primary key
    packfile_id BLOB NOT NULL,          -- the packfile ID, UNIQUE INDEX, [32]byte
    blob_count INTEGER NOT NULL,        -- number of blobs in packfile
    type TEXT NOT NULL,                 -- type of packfile data/tree
    --CONSTRAINT ux_pfiles_pack           UNIQUE(packfile_id)
    packfile_size INTEGER NOT NULL      -- data length of packfile
)`,

  `CREATE TABLE index_repo (
    id INTEGER PRIMARY KEY,             -- the primary key
    blob BLOB NOT NULL,                 -- the id, UNIQUE INDEX, [32]byte
    type TEXT NOT NULL,                 -- type tree / data
    length INTEGER NOT NULL,            -- length of blob
    uncompressedlength INTEGER NOT NULL,-- uncompressed length
    pack__id INTEGER NOT NULL,          -- back ptr to packflies, INDEX
    FOREIGN KEY(pack__id)               REFERENCES packfiles(id)
    --CONSTRAINT ux_index_repo_blob       UNIQUE(blob)
)`,

  `CREATE TABLE names (
    id INTEGER PRIMARY KEY,             -- the primary key
    name TEXT NOT NULL                 -- all base names, UNIQUE
    --CONSTRAINT ux_names_name            UNIQUE(name)
)`,

  `CREATE TABLE meta_data_store (
    id INTEGER PRIMARY KEY,
    blob__id INTEGER NOT NULL,          -- back ptr to index_repo UNIQUE KEY, part 1
    position INTEGER NOT NULL,          -- offset into slice      UNIQUE KEY, part 2
    name__id INTEGER NOT NULL,          -- pointer to name
    type TEXT NOT NULL,
    mode INTEGER NOT NULL,
    mtime TEXT NOT NULL,
    inode INTEGER NOT NULL,
    deviceid INTEGER NOT NULL,
    sha256__id INTEGER,                 -- can be NULL if not enabled
    size INTEGER,                       -- can be NULL for dir, empty file, symlink
    links INTEGER,                      -- can be NULL for dir
    subtree__id INTEGER,                -- can be NULL for      file, symlink
    linktarget TEXT,                    -- can be NULL for dir, file

    FOREIGN KEY(blob__id)               REFERENCES index_repo(id),
    FOREIGN KEY(name__id)               REFERENCES names(id)
    --CONSTRAINT ux_mds_id_blob           UNIQUE(blob__id, position)
)`,

  `CREATE TABLE contents (
    id INTEGER PRIMARY KEY,             -- with ROWID, it is a large table
    blob__id INTEGER NOT NULL,          -- ptr to idd_file,        UNIQUE KEY, part 1
    position INTEGER NOT NULL,          -- position in file slice, UNIQUE KEY, part 2
    offset   INTEGER NOT NULL,          -- offset into contents    UNIQUE KEY, part 3
    data__id INTEGER NOT NULL,          -- ptr to ixr.id, INDEX
    FOREIGN KEY(data__id)               REFERENCES index_repo(id),
    FOREIGN KEY(blob__id)               REFERENCES index_repo(id)
    --CONSTRAINT ux_cont_idblof           UNIQUE(blob__id, position, offset)
)`,

  `CREATE TABLE config (
     id INTEGER PRIMARY KEY,            -- the primary key = 1
     repo_id TEXT NOT NULL,             -- repository ID
     chunker_polynomial TEXT,           -- chunker polynomial for encoding
     repo_path TEXT,                    -- fullpath to repo
     sha256_context TEXT,               -- enable / disable sha256_content
     empty_node_id INTEGER,             -- points to index_repo(EMPTY_NODE_ID)
     last_snap_time TEXT,               -- youngest snap
     last_index_time TEXT              -- youngest index change
)`,

  `CREATE TABLE sha256_content (
     id INTEGER PRIMARY KEY,            -- the primary key
     sha256 BLOB,                       -- UNIQUE INDEX for content slice
     length INTEGER                     -- number of data blobs for file
     --CONSTRAINT ux_sha256_sha UNIQUE(sha256)
)`,

  // derived tables, can be created from the above tables
  // not filled during initial load

  // WITHOUT ROWID tables do their own thing regarding INDEXing,
  // so it is not worth having CREATE INDEX on those tables!
  // or sorting the primary keys before INSERT
  `CREATE TABLE children (
    parent__id INTEGER NOT NULL,        -- parent entry
    child__id  INTEGER NOT NULL,        -- child  entry

    PRIMARY KEY(parent__id, child__id), -- UNIQUE
    FOREIGN KEY(parent__id)             REFERENCES index_repo(id),
    FOREIGN KEY(child__id)              REFERENCES index_repo(id)
) WITHOUT ROWID`,

  `CREATE TABLE fullname (
    id INTEGER PRIMARY KEY,             -- the primary key, autogenerated
    pathname TEXT NOT NULL              -- full pathname of directory, UNIQUE INDEX
    --CONSTRAINT ux_fname_path            UNIQUE(pathname)
)`,

  `CREATE TABLE dir_path (
    blob__id INTEGER PRIMARY KEY,       -- the primary key = ixr.id
    fullname__id INTEGER NOT NULL,      -- ptr to "fullname", INDEX
    FOREIGN KEY(fullname__id)           REFERENCES fullname(id),
    FOREIGN KEY(blob__id)               REFERENCES index_repo(id)
)`,

  `CREATE TABLE snap_blobs (
    snap__id INTEGER NOT NULL,          -- the snap_id pointer
    blob__id INTEGER NOT NULL,          -- the blob pointer
    PRIMARY KEY(snap__id, blob__id),    -- UNIQUE
    FOREIGN KEY(snap__id)               REFERENCES snapshots(id),
    FOREIGN KEY(blob__id)               REFERENCES index_repo(id)
) WITHOUT ROWID`,
}

var CreateIndexSlice = []string{
  // UNIQUE index
  `CREATE UNIQUE INDEX IF NOT EXISTS ux_contents_blopoof ON contents(blob__id,position,offset)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS ux_fullname_path    ON fullname(pathname)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS ux_index_repo_blob  ON index_repo(blob)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS ux_mds_blopo        ON meta_data_store(blob__id,position)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS ux_names_name       ON names(name)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS ux_packfiles_pack   ON packfiles(packfile_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS ux_sha256_cont_shar ON sha256_content(sha256)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS ux_snapshots_snid   ON snapshots(snap_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS ux_snapshots_short  ON snapshots(snap_short)`,

  // normal INDEX
  `CREATE INDEX IF NOT EXISTS ix_snap_root   ON snapshots(snap_root)`,
  `CREATE INDEX IF NOT EXISTS ix_ixr_pack    ON index_repo(pack__id)`,
  `CREATE INDEX IF NOT EXISTS ix_ixr_type    ON index_repo(type)`,
  `CREATE INDEX IF NOT EXISTS ix_cont_data   ON contents(data__id)`,
  `CREATE INDEX IF NOT EXISTS ix_mds_type    ON meta_data_store(type)`,
  `CREATE INDEX IF NOT EXISTS ix_mds_name_id ON meta_data_store(name__id)`,
  `CREATE INDEX IF NOT EXISTS ix_mds_subtree ON meta_data_store(subtree__id)
     WHERE type='dir'`,
  `CREATE INDEX IF NOT EXISTS ix_mds_sha256  ON meta_data_store(sha256__id)
     WHERE type='file'`,
  `CREATE INDEX IF NOT EXISTS ix_sha256_len  ON sha256_content(length)`,
}

// create database name from globalOptions.Repo
func selectDatabaseName(gopts GlobalOptions) string {
  var dataBaseFilename string
  if strings.Contains(globalOptions.Repo, ":") {
    parts := strings.Split(globalOptions.Repo, ":")
    dataBaseFilename = fmt.Sprintf("/home/wplapper/restic/db/%s-%s.db",
      parts[1], parts[2])
  } else {
    dataBaseFilename = fmt.Sprintf("/home/wplapper/restic/db/%s.db",
      filepath.Base(globalOptions.Repo))
  }
  return dataBaseFilename
}

func processAllIndexRepoFile(repositoryData *RepositoryData) error {
  path := "/home/wplapper/restic/all_index_repo.bin"
  indexRepoStat, err := os.Stat(path)
  var (
    handle           *os.File
    pos              IntID
    err2             error
    youngestDatabase string
  )
  if err == nil {
    handle, err2 = os.Open(path)
    if err2 != nil {
      panic("unexpeced error after Stat(all_index_repo.bin)")
    }
  }
  defer handle.Close()

  maxTime := time.Date(2006, 1, 2, 15, 4, 5, 0, time.UTC)
  youngestDatabase = "???"
  fileList, err := filepath.Glob("/home/wplapper/restic/db/*.db")
  if err != nil {
    Printf("Can't glob /home/wplapper/restic/db/*.db - error is '%v'\n", err)
    return err
  }

  // loop over all databases
  for _, filename := range fileList {
    out, err := exec.Command("/usr/bin/sqlite3", "-noheader", filename,
      "SELECT last_index_time FROM config WHERE id=1").CombinedOutput()
    if err != nil { // ignore
      continue
    }

    // get rid of trailing "\n"
    out_str := string(out)
    out_str = out_str[:len(out_str)-1]
    youngIndexTime, err := time.Parse("2006-01-02 15:04:05", out_str)
    if err != nil {
      Printf("time.Parse %s - error2 '%v'\n", filepath.Base(filename), err)
      continue
    }

    // find youngest file
    if youngIndexTime.After(maxTime) {
      maxTime = youngIndexTime
      youngestDatabase = filename
    }
  }

  if maxTime.After(indexRepoStat.ModTime()) {
    Printf("WARN: %s is older than the youngest of the database file!\n", path)
    Printf("Youngest database file %s is from %s\n", youngestDatabase,
      maxTime.Format(time.DateTime))
    Printf("index_file %s\n", indexRepoStat.ModTime().Format(time.DateTime))
  }

  if handle != nil {
    pos = IntID(2)
    for true { // read from handle until we hit io.EOF
      var HexId restic.ID
      err = binary.Read(handle, binary.LittleEndian, &HexId)
      if err != nil && errors.Is(err, io.EOF) {
        handle.Close()
        break
      }
      _, ok := repositoryData.BlobToIndex[HexId]
      if !ok {
        repositoryData.BlobToIndex[HexId] = pos
        repositoryData.IndexToBlob = append(repositoryData.IndexToBlob, HexId)
        pos++
      }
    }
  }
  return nil
}

func checkDatabaseDates(dataBaseFilename string, repo *repository.Repository,
  repositoryData *RepositoryData) (bool, error) {
  changeTimes, err := findLatestChanges(repo, repositoryData)
  if err != nil {
    return false, err
  }

  out, err := exec.Command("/usr/bin/sqlite3", "-noheader", dataBaseFilename,
    "SELECT last_index_time FROM config WHERE id=1").Output()
  if err != nil { // ignore
    return false, err
  }

  // get rid of trailing "\n"
  out_str := string(out)
  out_str = out_str[:len(out_str)-1]
  youngIndexTimeDB, err := time.Parse("2006-01-02 15:04:05", out_str)
  if err != nil {
    Printf("time.Parse - error3 '%v'\n", err)
    return false, err
  }

  out, err = exec.Command("/usr/bin/sqlite3", "-noheader", dataBaseFilename,
    "SELECT count(*) FROM index_repo").Output()
  if err != nil { // ignore
    return false, err
  }

  // get rid of trailing "\n"
  out_str = string(out)
  out_str = out_str[:len(out_str)-1]
  countIndexRepo, _ := strconv.ParseInt(out_str, 10, 64)
  if int(countIndexRepo) != len(repositoryData.IndexHandle) {
    Printf("FAIL: count memory %7d\n", len(repositoryData.IndexHandle))
    Printf("FAIL: count dtbase %7d\n", countIndexRepo)
    return false, nil
  }

  // it is the nanoseconds which can play havoc here, so we have to revert
  // to compare string representations
  youngIndexRecordStr := changeTimes.youngIndexRecord.Format(time.DateTime)
  youngIndexDBStr := youngIndexTimeDB.Format(time.DateTime)
  if youngIndexRecordStr == youngIndexDBStr {
    return true, nil
  } else {
    Printf("FAIL: last index file   change %s\n", youngIndexRecordStr)
    Printf("FAIL: last database rec. index %s\n", youngIndexRecordStr)
    return false, nil
  }
}

// serialize 'content' step by step into sha256 by Write-ing() to it
func ConvertContent(content []IntID) (result restic.ID) {
  sha256sum := sha256.New()
  temp := make([]byte, 4)
  for _, data_blob_int := range content {
    //binary.LittleEndian.PutUint32(temp, data_blob_int): serialize uint32
    temp[0] = byte(data_blob_int)
    temp[1] = byte(data_blob_int >> 8)
    temp[2] = byte(data_blob_int >> 16)
    temp[3] = byte(data_blob_int >> 24)
    sha256sum.Write(temp)
  }

  // copy final target to [sha256.Size]byte,
  // type 'sha256sum.Sum(nil)' is []byte
  // 'copy' can copy between different types
  copy(result[:], sha256sum.Sum(nil))
  return result
}
