package main

import (
	// system
	"context"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	//argparse
	"github.com/spf13/cobra"

	// restic library
	"github.com/wplapper/restic/library/repository"
	"github.com/wplapper/restic/library/restic"

	// sets
	"github.com/deckarep/golang-set/v2"
)

type CreateDB struct {
	Debug  string
	Index  bool
	Sha256 bool
}

const (
	DBG_SNAPSHOT = 0x004
	DBG_PACKFILE = 0x008
	DBG_INDEX    = 0x010
	DBG_NAMES    = 0x020
	DBG_METADATA = 0x040
	DBG_CONTENTS = 0x080
)

var createDBOptions CreateDB

var cmdCreateDB = &cobra.Command{
	Use:   "wpl-create-db [flags]",
	Short: "create sql statements for a SQLite database to be generated",
	Long: `create sql statements for a SQLite database to be generated.
Use the format of the sqlite3 .dump format for outputting the data straight
into sqlite:
/usr/bin/sqlite3 [database-name] < [input stream generated by this command].
os/exec.Command("/usr/bin/sqlite3", database-name) is used,
wehereby STDIN is connected to a pipe (exec.StdinPipe()).

EXIT STATUS
===========

Exit status is 0 if the command was successful, and non-zero if there was any error.
`,
	DisableAutoGenTag: false,
	RunE: func(cmd *cobra.Command, args []string) error {
		return runCreateDB(cmd.Context(), cmd, globalOptions)
	},
}

func init() {
	cmdRoot.AddCommand(cmdCreateDB)
	f := cmdCreateDB.Flags()
	f.StringVarP(&createDBOptions.Debug, "debug", "D", "0", "debug options")
	f.BoolVarP(&createDBOptions.Index, "no-index", "I", false, "do not create index tables")
	f.BoolVarP(&createDBOptions.Sha256, "sha256", "S", false, "do not create sha256 contents")
}

type Driver struct {
	stdin io.WriteCloser
	Debug int
}

func runCreateDB(ctx context.Context, cmd *cobra.Command, gopts GlobalOptions) error {

	var (
		repositoryData   RepositoryData
		dataBaseFilename string
		err              error
		startTime        time.Time
	)

	// startup
	startTime = time.Now()
	gOptions = gopts
	init_repositoryData(&repositoryData)

	// convert Debug string to int
	debug_options_str := createDBOptions.Debug
	debug_options_int := 0
	re := regexp.MustCompile("^[a-fA-F0-9]+$")
	if re.FindString(debug_options_str) != "" {
		temp, _ := strconv.ParseInt(debug_options_str, 16, 64)
		debug_options_int = int(temp)
	}

	// step 1: open repository
	repo, err := OpenRepository(ctx, gopts)
	if err != nil {
		return err
	}
	Verboseff("Repository is %s\n", gopts.Repo)
	Verboseff("%-48s %7.1f seconds\n", "repository open",
		time.Since(startTime).Seconds())

	// step 2: gather the base information
	err = gather_base_data_repo(repo, gopts, ctx, &repositoryData,
		repo_details_options.Timing)
	if err != nil {
		return err
	}
	Verboseff("%-48s %7.1f seconds\n", "gather base data",
		time.Since(startTime).Seconds())

	if createDBOptions.Index {
		dataBaseFilename = fmt.Sprintf("/home/wplapper/restic/db/%s-woix.db",
			filepath.Base(gopts.Repo))
	} else {
		dataBaseFilename = fmt.Sprintf("/home/wplapper/restic/db/%s.db",
			filepath.Base(gopts.Repo))
	}
	Verboseff("database is %s\n", dataBaseFilename)

	_, err = os.Create(dataBaseFilename)
	if err != nil {
		Printf("Cant Create database - reason '%v'\n", err)
		return err
	}

	err = os.Chown(dataBaseFilename, 1000, 1000)
	if err != nil {
		Printf("Cant Chown database - reason '%v'\n", err)
		return err
	}

	sqlCmd := exec.Command("/usr/bin/sqlite3", dataBaseFilename)
	stdin, err := sqlCmd.StdinPipe()
	if err != nil {
		Printf("Cant Create Pipe to STDIN - reason '%v'\n", err)
		return err
	}

	go func() {
		defer stdin.Close()
		driver := &Driver{stdin, debug_options_int}
		// generate the input stream for the SQLite database
		GatherDatabaseData(ctx, repo, driver, &repositoryData, startTime)
	}()

	// wait for the external command execution to finish
	out, err := sqlCmd.CombinedOutput()
	if err != nil {
		Printf("CombinedOutput failed 	- reason '%v'\n", err)
		Printf("%s\n", out)
		return err
	}
	if len(out) > 0 {
		Printf("%s\n", out)
	}
	Verboseff("%-48s %7.1f seconds\n", "*** finale ***",
		time.Since(startTime).Seconds())
	return nil
}

func GatherDatabaseData(ctx context.Context, repo *repository.Repository,
	driver *Driver, repositoryData *RepositoryData, startTime time.Time) (err error) {
	/*
	 * sequence of events is as follows:
	 * the in-core file will be generated in the steps
	 * 00-startup
	 * 01-create_tables
	 * 02-snapshots
	 * 03-packfiles
	 * 04-index_repo
	 * 05-names
	 * metaBlobSorter
	 * 09-createSha56
	 * 06-meta_data_storage (needs all the above dependencies)
	 * 06-meta_data_storage (needs all the above dependencies)
	 * 07-contents
	 * 08-config (single row table)
	 * 12-create_index
	 * 13-finale
	 *
	 * The following tables can easily be created by running a few SQL statements:
	 * children
	 * snap_blobs
	 * dir_names, for use in creating fullname
	 */
	 var sha256Content map[CmpIndex]int

	step_00_startup     (driver)
	step_01_createTables(driver)
	step_02_snapshots   (driver, repositoryData, startTime) // 02-snapshots
	step_03_04_ix_files (driver, repositoryData, startTime) // 03-packfiles, 04-index_repo
	namesMap := step_05_names(driver, repositoryData, startTime)
	metaBlobs := MetaBlobSorter(repositoryData)

	if createDBOptions.Sha256 {
		sha256Content = map[CmpIndex]int{}
	} else {
		sha256Content = step_09_createSha56(driver, repositoryData)
	}

	step_06_meta_data_storage(ctx, repo, driver, repositoryData, namesMap,
		metaBlobs, sha256Content, startTime)
	step_07_contents(driver, repositoryData, metaBlobs, startTime)
	step_08_repo_config(driver, repo, !createDBOptions.Sha256)

	if !createDBOptions.Index {
		step_12_createIndex(driver)
	}

	step_13_finale(driver)
	Verboseff("%-48s %7.1f seconds\n", "end create stream",
		time.Since(startTime).Seconds())
	return nil
}

// start the export file
func step_00_startup(tx *Driver) {
	io.WriteString(tx.stdin, "PRAGMA foreign_keys=OFF;\n")
	io.WriteString(tx.stdin, "BEGIN EXCLUSIVE TRANSACTION;\n")
}

// and CREATE TABLEs
func step_01_createTables(tx *Driver) {
	for _, sql := range CreateTablesSlice {
		io.WriteString(tx.stdin, sql+";\n")
	}
}

// gather data about snapshots
func step_02_snapshots(tx *Driver, repositoryData *RepositoryData,
	startTime time.Time) (snapMap map[restic.ID]int) {

	/*
		type SnapshotRow struct {
			Id        int
			Snap_id   []byte
			Snap_short string (8 bytes long)
			Snap_time string
			Snap_host string
			Snap_fsys string
			Snap_root []byte
		}
	*/
	high_id := 1
	snapMap = map[restic.ID]int{}
	// repositoryData.Snaps is already sorted
	for _, sn := range repositoryData.Snaps {
		ID := sn.ID
		snap_id_as_string := hex.EncodeToString(ID[:])
		line := fmt.Sprintf(
			"INSERT INTO snapshots VALUES(%d,X'%s','%s','%s','%s','%s',X'%s');\n",
			high_id,
			snap_id_as_string,
			snap_id_as_string[:8],
			sn.Time.Format(time.DateTime),
			sn.Hostname, sn.Paths[0],
			hex.EncodeToString(sn.Tree[:]))
		io.WriteString(tx.stdin, line)
		if (tx.Debug & DBG_SNAPSHOT) == DBG_SNAPSHOT {
			Printf("%s", line)
		}
		snapMap[ID] = high_id
		high_id++
	}
	Verboseff("%-35s %7d rows %7.1f seconds\n", "INSERT INTO snapshots",
		high_id-1, time.Since(startTime).Seconds())
	return snapMap
}

type PackfileRecordRow struct {
	Type string
}

// gather information about packfiles and the index structure
func step_03_04_ix_files(tx *Driver, repositoryData *RepositoryData,
	start time.Time) {

	// gather all packfile IDs
	packMap := map[restic.ID]PackfileRecordRow{}
	packSet := mapset.NewThreadUnsafeSet[int]()
	packToBlobSet := map[IntID]mapset.Set[IntID]{}
	for _, ih := range repositoryData.IndexHandle {
		if packSet.Add(int(ih.pack_index)) {
			pack_ID := repositoryData.IndexToBlob[ih.pack_index]
			row := PackfileRecordRow{ih.Type.String()}
			packMap[pack_ID] = row
		}
		if _, ok := packToBlobSet[ih.pack_index]; !ok {
			packToBlobSet[ih.pack_index] = mapset.NewThreadUnsafeSet[IntID]()
		}
		packToBlobSet[ih.pack_index].Add(ih.blob_index)
	}

	// convert to Slice and sort
	packSlice := packSet.ToSlice()
	sort.Ints(packSlice)
	/*CREATE TABLE packfiles (
			id INTEGER PRIMARY KEY,             -- the primary key
			packfile_id BLOB NOT NULL,          -- the packfile ID, UNIQUE INDEX, [32]byte
			blob_count INTEGER NOT NULL,        -- number of blobs in packfile
			type TEXT NOT NULL                  -- type of packfile data/tree
	)*/

	count := 0
	for _, pack_index := range packSlice {
		pack_ID := repositoryData.IndexToBlob[IntID(pack_index)]
		row := packMap[pack_ID]
		line := fmt.Sprintf("INSERT INTO packfiles VALUES(%d,X'%s',%d,'%s');\n",
			pack_index, hex.EncodeToString(pack_ID[:]),
				packToBlobSet[IntID(pack_index)].Cardinality(), row.Type)
		io.WriteString(tx.stdin, line)
		if (tx.Debug & DBG_PACKFILE) == DBG_PACKFILE {
			Printf("%s", line)
		}
		count++
	}
	Verboseff("%-35s %7d rows %7.1f seconds\n", "INSERT INTO packfiles",
		count, time.Since(start).Seconds())

	/*type IndexRepoRecordRow struct {
			Id                 IntID
			Blob               []byte // == UNIQUE
			Type               string
			Length             int
			UncompressedLength int
			Pack__id           int // back pointer to packfiles
		}*/

	// collect all blob indices - tree and data
	blobSet := mapset.NewThreadUnsafeSet[int]()
	for _, ih := range repositoryData.IndexHandle {
		blobSet.Add(int(ih.blob_index))
	}

	// convert to Slice and sort
	blobSlice := blobSet.ToSlice()
	sort.Ints(blobSlice)
	count = 0
	for _, blob_index := range blobSlice {
		blob_ID := repositoryData.IndexToBlob[IntID(blob_index)]
		ih := repositoryData.IndexHandle[blob_ID]

		line := fmt.Sprintf("INSERT INTO index_repo VALUES(%d,X'%s','%s',%d,%d,%d);\n",
			blob_index,
			hex.EncodeToString(blob_ID[:]),
			ih.Type.String(),
			ih.size,
			ih.UncompressedLength,
			ih.pack_index)
		io.WriteString(tx.stdin, line)
		if (tx.Debug & DBG_INDEX) == DBG_INDEX {
			Printf("%s", line)
		}
		count++
	}

	Verboseff("%-35s %7d rows %7.1f seconds\n", "INSERT INTO index_repo",
		count, time.Since(start).Seconds())
}

// collect all names from repository
func step_05_names(tx *Driver, repositoryData *RepositoryData,
	start time.Time) (namesMap map[string]int) {

	// gather names
	namesSet := mapset.NewThreadUnsafeSet[string]()
	for _, fileList := range repositoryData.DirectoryMap {
		for _, node := range fileList {
			namesSet.Add(node.name)
		}
	}

	// convert Set to Slice for sorting
	namesSlice := namesSet.ToSlice()
	sort.Strings(namesSlice)



	high_id := 1
	namesMap = map[string]int{}
	for _, name := range namesSlice {
		var nameDB string
		nameDB = name
		if strings.Index(nameDB, "'") >= 0 {
			nameDB = strings.ReplaceAll(nameDB, "'", "''")
		}
		line := fmt.Sprintf("INSERT INTO names VALUES(%d,'%s');\n", high_id, nameDB)
		io.WriteString(tx.stdin, line)
		if (tx.Debug & DBG_NAMES) == DBG_NAMES {
			Printf("%s", line)
		}
		namesMap[name] = high_id
		high_id++
	}

	Verboseff("%-35s %7d rows %7.1f seconds\n", "INSERT INTO names",
		high_id-1, time.Since(start).Seconds())
	return namesMap
}

// create a Slice of sorted metaBlobs - tree index records
func MetaBlobSorter(repositoryData *RepositoryData) (metaBlobs []IntID) {
	metaBlobsSet := mapset.NewThreadUnsafeSet[IntID]()
	for _, ih := range repositoryData.IndexHandle {
		if ih.Type == restic.TreeBlob {
			metaBlobsSet.Add(ih.blob_index)
		}
	}
	metaBlobs = metaBlobsSet.ToSlice()
	sort.Slice(metaBlobs, func(i, j int) bool {
		return metaBlobs[i] < metaBlobs[j]
	})
	return metaBlobs
}

func step_06_meta_data_storage(ctx context.Context, repo *repository.Repository,
	tx *Driver, repositoryData *RepositoryData, namesMap map[string]int,
	metaBlobs []IntID, sha256StoreIndex map[CmpIndex]int, start time.Time) (err error) {

	/*
		type MetaDataStorageRow struct {
			Id       IntID // ptr to 'index_repo' TABLE
			Position int   // offset in nodes list
			Name__id int   // ptr to 'names' TABLE
			// copied from original Node:
			Type        string
			Mode        os.FileMode
			Mtime       string
			Inode       uint64
			DeviceID    uint64
			Size        uint64
			Links       uint64
			Subtree__id IntID
			LinkTarget  string
		}
	*/
	high_id := 1
	for _, meta_blob := range metaBlobs {
		for position, node := range repositoryData.DirectoryMap[meta_blob] {
			var size, links, subtree__id, linkTarget, sha256 string

			// NULL column processing
			sha256 = "NULL"
			cmp_ix := CmpIndex{meta_blob, position}
			if len(sha256StoreIndex) > 1 && node.Type == "file" && node.size > 0 {
				index, ok := sha256StoreIndex[cmp_ix]
				if ok {
					sha256 = fmt.Sprintf("%d", index)
				} else {
					Printf("index entry %+v not found!\n", cmp_ix)
				}
			}
			if node.size == 0 {
				size = "NULL"
			} else {
				size = fmt.Sprintf("%d", node.size)
			}
			if node.Links == 0 {
				links = "NULL"
			} else {
				links = fmt.Sprintf("%d", node.Links)
			}
			if node.Type == "dir" {
				subtree__id = fmt.Sprintf("%d", node.subtree_ID)
			} else {
				subtree__id = "NULL"
			}
			if node.LinkTarget == "" {
				linkTarget = "NULL"
			} else {
				linkTarget = node.LinkTarget
				if strings.Index(linkTarget, "'") >= 0 {
					linkTarget = strings.ReplaceAll(linkTarget, "'", "''")
				}
				linkTarget = fmt.Sprintf("'%s'", linkTarget)
			}
			// end NULL processing

			line := fmt.Sprintf(
				"INSERT INTO meta_data_store VALUES(%d,%d,%d,%d,'%s',%d,'%s',%d,%d,"+
					"%s,%s,%s,%s,%s);\n",
				high_id,
				meta_blob,
				position,
				namesMap[node.name],
				node.Type,
				node.Mode,
				node.mtime.Format(time.DateTime),
				node.inode,
				node.DeviceID,
				// possible NULL values
				sha256,
				size,
				links,
				subtree__id,
				linkTarget)
			io.WriteString(tx.stdin, line)
			if (tx.Debug & DBG_METADATA) == DBG_METADATA {
				Printf("%s", line)
			}
			high_id++
		}
	}

	Verboseff("%-35s %7d rows %7.1f seconds\n", "INSERT INTO meta_data_store",
		high_id-1, time.Since(start).Seconds())
	return nil
}

// collect all names from repository
func step_07_contents(tx *Driver, repositoryData *RepositoryData,
	metaBlobs []IntID, start time.Time) {

	/*type ContentsRecordRow struct {
			Blob__id IntID // map back to index_repo.id (owning directory / meta_blob)
			Position int   // with triple (Id_blob, Position, Offset) == UNIQUE
			Offset   int
			Data__id IntID // map back to index_repo.id (data)
		}*/

	high_id := 1
	for _, meta_blob := range metaBlobs {
		for position, node := range repositoryData.DirectoryMap[meta_blob] {
			for offset, cont_value := range node.content {
				line := fmt.Sprintf("INSERT INTO contents VALUES(%d,%d,%d,%d,%d);\n",
					high_id,
					meta_blob,
					position,
					offset,
					cont_value)
				io.WriteString(tx.stdin, line)
				if (tx.Debug & DBG_CONTENTS) == DBG_CONTENTS {
					Printf("%s", line)
				}
				high_id++
			}
		}
	}

	Verboseff("%-35s %7d rows %7.1f seconds\n", "INSERT INTO contents",
		high_id-1, time.Since(start).Seconds())
}
/*CREATE TABLE config (
     id INTEGER PRIMARY KEY,            -- the primary key = 1
     repo_id TEXT NOT NULL,             -- repository ID
     chunker_polynomial TEXT,           -- chunker polynomial for encoding
     repo_path TEXT,                    -- fullpath to repo
     database_time TEXT                 -- when was this DB created
)*/

func step_08_repo_config(tx *Driver, repo *repository.Repository, sha256 bool) {
	config := repo.Config()
	chunker_polynomial := fmt.Sprintf("%v", config.ChunkerPolynomial) // 0x...
	// globalOptions.Repo
	var sha56Create string
	if sha256 {
		sha56Create = "true"
	} else {
		sha56Create = "false"
	}
	line := fmt.Sprintf("INSERT INTO config VALUES(%d,'%s','%s','%s','%s','%s');\n",
		1,
		config.ID,
		chunker_polynomial[2:],
		globalOptions.Repo,
		sha56Create,
		time.Now().Format(time.DateTime))
	io.WriteString(tx.stdin, line)
}

type CmpIndex struct {
	blob_index IntID
	position   int
}

func step_09_createSha56(tx *Driver, repositoryData *RepositoryData) (map[CmpIndex]int) {

	// set up slices, maps and constants
	sha256Map := map[[32]byte]int{}
	sha256StoreIndex := map[CmpIndex]int{}

	// this entry points to garbage
	data, _ := hex.DecodeString(strings.Repeat("deadbeef0caffee0", 4))
	var data2 [32]byte
	copy(data2[:], data)
	sha256Map[data2] = 0

	//loop start
	index := 1
	var position int
	var ok bool
	for blob_index, fileSlice := range repositoryData.DirectoryMap {
		for posi, meta := range fileSlice {
			if meta.Type == "file" {
				sha256Content := ConvertContent(meta.content)
				if position, ok = sha256Map[sha256Content]; !ok {
					position = index
					sha256Map[sha256Content] = position
					index++
				}
				sha256StoreIndex[CmpIndex{blob_index, posi}] = position
			}
		}
	}

	// write out 'sha256Slice'
	for value, index := range sha256Map {
		line := fmt.Sprintf("INSERT INTO sha256_content VALUES(%d,X'%s');\n",
			index, hex.EncodeToString(value[:]))
		io.WriteString(tx.stdin, line)
	}
	Verboseff("%-35s %7d rows\n", "INSERT INTO sha256_content", index)
	return sha256StoreIndex
}

// create all INDEX structures after all data have been inserted
func step_12_createIndex(tx *Driver) {
	for _, sql := range CreateIndexSlice {
		io.WriteString(tx.stdin, sql+";\n")
	}
}

// database export final steps
func step_13_finale(tx *Driver) {
	io.WriteString(tx.stdin, "COMMIT;\n")
	// CREATE left out secondary TABLE entries
	io.WriteString(tx.stdin, ".read /home/wplapper/restic/db/sql/create_missing_tables.sql\n")
}

// table definitions
var CreateTablesSlice = []string{
	`CREATE TABLE snapshots (
    id INTEGER PRIMARY KEY,             -- ID of snapshots row
    snap_id    BLOB NOT NULL,           -- snap ID, UNIQUE INDEX
    snap_short TEXT NOT NULL,           -- snap ID, first 8 character as string
    snap_time  TEXT NOT NULL,           -- time of snap, truncated to seconds
    snap_host  TEXT NOT NULL,           -- host which is to be backep up
    snap_fsys  TEXT NOT NULL,           -- filesystem to be backup up
    snap_root  BLOB NOT NULL            -- the root of the snap
)`,

	`CREATE TABLE packfiles (
    id INTEGER PRIMARY KEY,             -- the primary key
    packfile_id BLOB NOT NULL,          -- the packfile ID, UNIQUE INDEX, [32]byte
    blob_count INTEGER NOT NULL,        -- number of blobs in packfile
    type TEXT NOT NULL                  -- type of packfile data/tree
)`,

	`CREATE TABLE index_repo (
    id INTEGER PRIMARY KEY,             -- the primary key
    blob BLOB NOT NULL,                 -- the id, UNIQUE INDEX, [32]byte
    type TEXT NOT NULL,                 -- type tree / data
    length INTEGER NOT NULL,            -- length of blob
    uncompressedlength INTEGER NOT NULL,-- uncompressed length
    pack__id INTEGER NOT NULL,          -- back ptr to packflies, INDEX
    FOREIGN KEY(pack__id)               REFERENCES packfiles(id)
)`,

	`CREATE TABLE names (
    id INTEGER PRIMARY KEY,             -- the primary key
    name TEXT NOT NULL                  -- all base names, UNIQUE
)`,

	`CREATE TABLE meta_data_store (
    id INTEGER PRIMARY KEY,
    blob__id INTEGER NOT NULL,          -- back ptr to index_repo UNIQUE KEY, part 1
    position INTEGER NOT NULL,          -- offset into slice      UNIQUE KEY, part 2
    name__id INTEGER NOT NULL,          -- pointer to name
    type TEXT NOT NULL,
    mode INTEGER NOT NULL,
    mtime TEXT NOT NULL,
    inode INTEGER NOT NULL,
    deviceid INTEGER NOT NULL,
    sha256__id INTEGER,                 -- can be NULL if not enabled
    size INTEGER,                       -- can be NULL for dir, empty file, symlink
    links INTEGER,                      -- can be NULL for dir
    subtree__id INTEGER,                -- can be NULL for      file, symlink
    linktarget TEXT,                    -- can be NULL for dir, file

    FOREIGN KEY(blob__id)               REFERENCES index_repo(id)
    FOREIGN KEY(name__id)               REFERENCES names(id)
)`,

	`CREATE TABLE contents (
    id INTEGER PRIMARY KEY,             -- with ROWID, it is a large table
    blob__id INTEGER NOT NULL,          -- ptr to idd_file,        UNIQUE KEY, part 1
    position INTEGER NOT NULL,          -- position in file slice, UNIQUE KEY, part 2
    offset   INTEGER NOT NULL,          -- offset into contents    UNIQUE KEY, part 3
    data__id INTEGER NOT NULL,          -- ptr to ixr.id, INDEX
    FOREIGN KEY(data__id)               REFERENCES index_repo(id),
    FOREIGN KEY(blob__id)               REFERENCES index_repo(id)
)`,

	`CREATE TABLE config (
     id INTEGER PRIMARY KEY,            -- the primary key = 1
     repo_id TEXT NOT NULL,             -- repository ID
     chunker_polynomial TEXT,           -- chunker polynomial for encoding
     repo_path TEXT,                    -- fullpath to repo
     sha256_context TEXT,               -- enable / disable sha256_content
     database_time TEXT                 -- when was this DB created
)`,

	`CREATE TABLE sha256_content (
     id INTEGER PRIMARY KEY,            -- the primary key
     sha256 BLOB                        -- UNIQUE INDEX for content slice
)`,

	// derived tables, can be created from the above tables
	// not filled during initial load

	// WITHOUT ROWID tables do their own thing regarding INDEXing,
	// so it is not worth having CREATE INDEX on those tables!
	// or sorting the primary keys before INSERT
	`CREATE TABLE children (
    parent__id INTEGER NOT NULL,        -- parent entry
    child__id  INTEGER NOT NULL,        -- child  entry

    PRIMARY KEY(parent__id, child__id), -- UNIQUE
    FOREIGN KEY(parent__id)             REFERENCES index_repo(id),
    FOREIGN KEY(child__id)              REFERENCES index_repo(id)
) WITHOUT ROWID`,

	`CREATE TABLE fullname (
    id INTEGER PRIMARY KEY,             -- the primary key, autogenerated
    pathname TEXT NOT NULL              -- full pathname of directory, UNIQUE INDEX
)`,

	`CREATE TABLE dir_path (
    blob__id INTEGER PRIMARY KEY,       -- the primary key = ixr.id
    fullname__id INTEGER NOT NULL,      -- ptr to "fullname", INDEX
    FOREIGN KEY(fullname__id)           REFERENCES fullname(id),
    FOREIGN KEY(blob__id)               REFERENCES index_repo(id)
)`,

	`CREATE TABLE snap_blobs (
    snap__id INTEGER NOT NULL,          -- the snap_id pointer
    blob__id INTEGER NOT NULL,          -- the blob pointer
    PRIMARY KEY(snap__id, blob__id),    -- UNIQUE
    FOREIGN KEY(snap__id)               REFERENCES snapshots(id),
    FOREIGN KEY(blob__id)               REFERENCES index_repo(id)
) WITHOUT ROWID`,
}

var CreateIndexSlice = []string{
	// UNIQUE INDEX - alternate primary keys
	`CREATE UNIQUE INDEX IF NOT EXISTS ux_ss_snapid   ON snapshots(snap_id)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS ux_pack_packON packfiles(packfile_id)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS ux_ixr_blob    ON index_repo(blob)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS ux_names_name  ON names(name)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS ux_mds_blpo    ON meta_data_store(blob__id,position)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS ux_cont_blpoof ON contents(blob__id,position,offset)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS ux_fname_path  ON fullname(pathname)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS ux_sha256_sha  ON sha256_content(sha256)`,

	// normal INDEX
	`CREATE        INDEX IF NOT EXISTS ix_ixr_pack    ON index_repo(pack__id)`,
	`CREATE        INDEX IF NOT EXISTS ix_ixr_type    ON index_repo(type)`,
	`CREATE        INDEX IF NOT EXISTS ix_cont_data   ON contents(data__id)`,
	`CREATE        INDEX IF NOT EXISTS ix_mds_type    ON meta_data_store(type)`,
	`CREATE        INDEX IF NOT EXISTS ix_mds_name_id ON meta_data_store(name__id)`,
	`CREATE        INDEX IF NOT EXISTS ix_mds_subtree ON meta_data_store(subtree__id)
     WHERE type='dir'`,
	`CREATE        INDEX IF NOT EXISTS ix_mds_sha256  ON meta_data_store(sha256__id)
     WHERE type='file'`,
}
